version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && psql ratestask < rates.sql && python manage.py runserver 0.0.0.0:8000"
    container_name: music_service
    volumes:
      - .:/music_service
    ports:
      - "8000:8000"